# Generated by Django 4.1.3 on 2022-11-23 07:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_reference',
            field=models.UUIDField(default=uuid.UUID('b85ede90-55b6-45a4-9656-cb1413b0b7a2')),
        ),
    ]
