# Generated by Django 4.1.3 on 2022-11-23 07:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_order_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_reference',
            field=models.UUIDField(default=uuid.UUID('54028689-55bf-44cb-bda8-5721d0a31b4b')),
        ),
    ]
