# Generated by Django 4.1.3 on 2022-11-23 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_order_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_reference',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
