# Generated by Django 4.1.3 on 2022-12-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='nickname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
