# Generated by Django 4.1.3 on 2022-12-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_orderitem_color_alter_orderitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_items_count',
            field=models.IntegerField(default=1),
        ),
    ]
