# Generated by Django 4.1.3 on 2022-11-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
