# Generated by Django 4.1.3 on 2022-11-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0002_product_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='assets/')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
