# Generated by Django 4.1.3 on 2022-11-23 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0003_images_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mart.product'),
        ),
    ]
