# Generated by Django 4.1.3 on 2022-11-24 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0004_images_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name_plural': 'Images'},
        ),
    ]
