# Generated by Django 4.1.3 on 2022-11-24 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0008_product_brand_product_color_product_lengths_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slide',
            field=models.ManyToManyField(blank=True, related_name='slided', to='mart.product'),
        ),
    ]
