# Generated by Django 4.1.3 on 2022-11-24 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0009_product_slide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='occasion',
        ),
        migrations.DeleteModel(
            name='Occasion',
        ),
    ]
