# Generated by Django 4.1.3 on 2022-11-24 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0010_remove_product_occasion_delete_occasion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occasion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occasion_name', models.CharField(blank=True, max_length=15, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Occasions',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='occasion',
            field=models.ManyToManyField(blank=True, related_name='occusioned', to='mart.occasion'),
        ),
    ]
