# Generated by Django 4.1.3 on 2022-12-14 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0013_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='reviwed_at',
            new_name='reviewed_at',
        ),
    ]
