# Generated by Django 4.1.3 on 2022-12-18 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0014_rename_reviwed_at_reviews_reviewed_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={},
        ),
    ]
