# Generated by Django 4.1.3 on 2022-12-18 11:22

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0016_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcates', to='mart.genre'),
        ),
    ]
