# Generated by Django 4.1.3 on 2022-12-19 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0018_alter_product_category_taga'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taga',
            name='parent',
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Taga',
        ),
    ]
