# Generated by Django 4.1.3 on 2022-12-19 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0019_remove_taga_parent_alter_categories_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={},
        ),
    ]
