# Generated by Django 4.1.4 on 2022-12-21 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0021_alter_categories_options_genre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genre',
            new_name='Category',
        ),
    ]
