# Generated by Django 4.1.4 on 2022-12-21 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0025_remove_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categorys',
            new_name='category',
        ),
    ]
